version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse_proxy/configurations:/etc/nginx/conf.d
      - ./reverse_proxy/logs:/var/log/nginx
    ports:
      - "5004:81"
    networks:
      - home-server
  
  frontend:
    build: ./ClientApp
    stdin_open: true
    networks:
      - home-server
  
  backend:
    build: ./backend
    env_file: ".env"
    networks:
      - home-server


networks:
  home-server:
    external: true


