# pull official base image
# FROM node:13.12.0-alpine
# FROM node:latest
FROM node:16.16.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1 -g 
RUN npm install -g serve

# add app
COPY . ./

RUN npm run-script build
# RUN mv ./build/static ./build/spotify-static

# start app
CMD ["serve", "-s", "build"]
